// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8y-dgQAjZFBYMeoy42WzeHn46lIn9PaQ',
    appId: '1:751281868992:android:a6e065600c914e3b90dd25',
    messagingSenderId: '751281868992',
    projectId: 'quizapp-ac3dc',
    storageBucket: 'quizapp-ac3dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEfmW4SsHfgLIGSTk19WcxbZU9BRoUJCA',
    appId: '1:751281868992:ios:aac9525c423ed8fb90dd25',
    messagingSenderId: '751281868992',
    projectId: 'quizapp-ac3dc',
    storageBucket: 'quizapp-ac3dc.appspot.com',
    androidClientId: '751281868992-fcnh6mi5as354lg5sb5q3l69bok23ets.apps.googleusercontent.com',
    iosClientId: '751281868992-umpdqg1btno479d2quf8rj7lu7jechvh.apps.googleusercontent.com',
    iosBundleId: 'io.fireship.quizapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEfmW4SsHfgLIGSTk19WcxbZU9BRoUJCA',
    appId: '1:751281868992:ios:aac9525c423ed8fb90dd25',
    messagingSenderId: '751281868992',
    projectId: 'quizapp-ac3dc',
    storageBucket: 'quizapp-ac3dc.appspot.com',
    androidClientId: '751281868992-fcnh6mi5as354lg5sb5q3l69bok23ets.apps.googleusercontent.com',
    iosClientId: '751281868992-umpdqg1btno479d2quf8rj7lu7jechvh.apps.googleusercontent.com',
    iosBundleId: 'io.fireship.quizapp',
  );
}
